### ISSUE TITLE
Store is currently not supported

### ISSUE THREAD

**Issue by thomasgroch** [languitar/pass-git-helper#14]
Hi.
I just finished the whole setup of my environment and came across this log message.
 
`INFO:root:Action store is currently not supported`

I really liked the way this project works, but without the ability to auto add the records I feel I will have even more work than continuing with Apple's Keychain.

I would like someone to point me in the right direction regarding this problem (which should not be mine alone).

Thanks

**Comment by languitar** [comment]
I never needed that feature so far, because I always assumed that if I am using a service, I have previously registered with that service and generated credentials inside the password store during that stage. Hence, credentials are available once you first use git (which is usually after registering through the browser). Why doesn't this assumption work for you? Do you start with a fresh password store and use it only for git? Or what is the exact use case?

**Comment by thomasgroch** [comment]
Oh, now I get it. There really is no need for store function as it would be used just a few times per user.

I'm trying to cover some of use case from the Apple Keychain. It stores some records called "app's password" and WiFi passwords.

I also don't have a way to generate credentials without leaving the browser. But I believe it will [soon will be possible](https://github.com/browserpass/browserpass-extension/pull/143).

**Comment by languitar** [comment]
If you are using git, you have to leave the browser anyways. ;-)

So, if there is no further need for this from your side, I would vote to close this issue.
